// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TOTP")>]
[<assembly: AssemblyProductAttribute("TOTP")>]
[<assembly: AssemblyDescriptionAttribute("TOTP")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyCopyrightAttribute("2015")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TOTP"
    let [<Literal>] AssemblyProduct = "TOTP"
    let [<Literal>] AssemblyDescription = "TOTP"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyCopyright = "2015"
